name: carvita
description: "A manager for car maintainance."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  intl: any
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
