name: Flutter

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+\+[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.4
      
      - name: Decode Keystore
        env:
          APP_KEYSTORE_BASE64: ${{ secrets.APP_KEYSTORE_BASE64 }}
        run: |
          echo $APP_KEYSTORE_BASE64 | base64 --decode > android/app/app-keystore.jks
      
      - name: Create key.properties
        env:
          APP_KEY_ALIAS: ${{ secrets.APP_KEY_ALIAS }}
          APP_KEY_PASSWORD: ${{ secrets.APP_KEY_PASSWORD }}
          APP_KEYSTORE_PASSWORD: ${{ secrets.APP_KEYSTORE_PASSWORD }}
        run: |
          echo "storePassword=$APP_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$APP_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$APP_KEY_ALIAS" >> android/key.properties
          echo "storeFile=app-keystore.jks" >> android/key.properties

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Get Changelog
        id: get_change_log
        if: github.event_name == 'push'
        run: |
          tag=${{ github.ref_name }}
          version_code="${tag#*+}"
          changelog_file="fastlane/metadata/android/en-US/changelogs/${version_code}.txt"
          if [ ! -f "$changelog_file" ]; then
            echo "Changelog file '$changelog_file' not found!"
            exit 1
          fi
          echo "path=$changelog_file" >> "$GITHUB_OUTPUT"

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          files: build/app/outputs/apk/release/app-release.apk
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: ${{ steps.get_change_log.outputs.path }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: carvita-release-universal.apk
          path: build/app/outputs/apk/release/app-release.apk
