name: Flutter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.3
      
      - name: Decode Keystore
        env:
          APP_KEYSTORE_BASE64: ${{ secrets.APP_KEYSTORE_BASE64 }}
        run: |
          echo $APP_KEYSTORE_BASE64 | base64 --decode > android/app-keystore.jks
      
      - name: Create key.properties
        env:
          APP_KEY_ALIAS: ${{ secrets.APP_KEY_ALIAS }}
          APP_KEY_PASSWORD: ${{ secrets.APP_KEY_PASSWORD }}
          APP_KEYSTORE_PASSWORD: ${{ secrets.APP_KEYSTORE_PASSWORD }}
        run: |
          echo "storePassword=$APP_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$APP_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$APP_KEY_ALIAS" >> android/key.properties
          echo "storeFile=app-keystore.jks" >> android/key.properties

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: carvita-release-universal.apk
          path: build/app/outputs/apk/release/app-release.apk
